### ISSUE TITLE
Overflow error when using it with Hero

### ISSUE THREAD

**Issue by hyungtaecf** [aliyigitbireroglu/flutter-animated-overflow#1]
════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 120 pixels on the right.
The relevant error-causing widget was
    AnimatedOverflow 
lib\…\list\list_items.dart:191
════════════════════════════════════════════════════════════════════════════════

It is thrown for few milliseconds showing the yellow overflow bar when using it in the Hero widget. I tried it wrapping it in the AutoSizeText widget, and throwing this in its overflowReplacement property, but the problem persists.

**Comment by aliyigitbireroglu** [comment]
This shouldn't be a problem with an actual release build, if I am not mistaken. Most probably those few milliseconds are when the library is calculating the size of the content.
